{
 "title": "Weather",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "City",
    "query": "SHOW TAG VALUES WITH KEY = \"city\" "
   }
  ]
 },
 "panels": [
  {
   "title": "Sunrise",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "weather",
     "query": "SELECT last(\"sunrise\") FROM \"weather\"WHERE (\"city\" =~ /^$City$/)",
     "select": [
      [
       { "params": [ "sunrise" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "city", "operator": "=", "value": "Paris" }
     ]
    }
   ]
  },
  {
   "title": "Sunset",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "weather",
     "query": "SELECT last(\"sunset\") FROM \"weather\"WHERE (\"city\" =~ /^$City$/)",
     "select": [
      [
       { "params": [ "sunset" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "city", "operator": "=", "value": "Paris" }
     ]
    }
   ]
  },
  {
   "title": "Wind",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "query": "SELECT mean(\"wind\") FROM \"weather\" WHERE (\"city\" =~ /^$City$/)  GROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "city", "operator": "=~", "value": "/^$City$/" }
     ]
    }
   ]
  },
  {
   "title": "Visibility",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "weather",
     "query": "SELECT last(\"visibility\") FROM \"weather\"WHERE (\"city\" =~ /^$City$/)",
     "select": [
      [
       { "params": [ "visibility" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "city", "operator": "=", "value": "Paris" }
     ]
    }
   ]
  },
  {
   "title": "Sky",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "weather",
     "query": "SELECT last(\"description\") FROM \"weather\"WHERE (\"city\" =~ /^$City$/)",
     "select": [
      [
       { "params": [ "description" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "city", "operator": "=", "value": "Paris" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "query": "SELECT mean(\"temp\") FROM \"weather\" WHERE (\"city\" = 'Paris') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "city", "operator": "=~", "value": "/^$City$/" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "city", "operator": "=~", "value": "/^$City$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Temp",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "query": "SELECT mean(\"temp\") FROM \"weather\" WHERE (\"city\" =~ /^$City$/)  GROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "city", "operator": "=~", "value": "/^$City$/" }
     ]
    },
    {
     "alias": "Feels like",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "query": "SELECT mean(\"feels_like\") FROM \"weather\" WHERE (\"city\" =~ /^$City$/)  GROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "feels_like" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "city", "operator": "=~", "value": "/^$City$/" }
     ]
    },
    {
     "alias": "Temp min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "query": "SELECT mean(\"temp_min\") FROM \"weather\" WHERE (\"city\" =~ /^$City$/)  GROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "temp_min" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "city", "operator": "=~", "value": "/^$City$/" }
     ]
    },
    {
     "alias": "Temp max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "query": "SELECT mean(\"temp_max\") FROM \"weather\" WHERE (\"city\" =~ /^$City$/)  GROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "temp_max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "city", "operator": "=~", "value": "/^$City$/" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "query": "SELECT mean(\"humidity\") FROM \"weather\" WHERE (\"city\" =~ /^$City$/)  GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cloudiness",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "query": "SELECT mean(\"humidity\") FROM \"weather\" WHERE (\"city\" =~ /^$City$/)  GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "clouds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Rain",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "weather",
     "query": "select \"humidity\" from forecast  ",
     "select": [
      [
       { "params": [ "rain" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "city", "operator": "=~", "value": "/^$City$/" }
     ]
    }
   ]
  }
 ]
}