{
 "title": "Forecast",
 "time": { "from": "now", "to": "now+48h" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "City",
    "query": "SHOW TAG VALUES FROM \"forecast\" WITH KEY = \"city\"  "
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Feels like",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "forecast",
     "query": "select \"feels_like\" from forecast  ",
     "select": [
      [
       { "params": [ "temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "city", "operator": "=~", "value": "/^$City$/" }
     ]
    }
   ]
  },
  {
   "title": "Probability of rain",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "forecast",
     "query": "select \"humidity\" from forecast  ",
     "select": [
      [
       { "params": [ "pop" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "city", "operator": "=~", "value": "/^$City$/" }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "forecast",
     "query": "select \"humidity\" from forecast  ",
     "select": [
      [
       { "params": [ "humidity" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "city", "operator": "=~", "value": "/^$City$/" }
     ]
    }
   ]
  },
  {
   "title": "Wind",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "velocityms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "forecast",
     "query": "select \"wind\" from forecast ",
     "select": [
      [
       { "params": [ "wind" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "city", "operator": "=~", "value": "/^$City$/" }
     ]
    }
   ]
  },
  {
   "title": "UV",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "forecast",
     "query": "select \"humidity\" from forecast  ",
     "select": [
      [
       { "params": [ "uvi" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "city", "operator": "=~", "value": "/^$City$/" }
     ]
    }
   ]
  },
  {
   "title": "Cloudiness",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "forecast",
     "query": "select \"humidity\" from forecast  ",
     "select": [
      [
       { "params": [ "clouds" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "city", "operator": "=~", "value": "/^$City$/" }
     ]
    }
   ]
  }
 ]
}